/**
 * @file utils/generator-helpers.ts
 * @description Shared utilities for markdown file generators.
 *
 * Used by generators/moodle.ts and generators/plugin.ts to avoid
 * duplicating write, timestamp, header, and safely across both modules.
 */

import { writeFileSync } from "fs";
import { globalCache }   from "../cache.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratorResult {
  file:     string;
  success:  boolean;
  error?:   string;
  skipped?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Writes content to a file and marks it fresh in the global cache.
 * Returns a failed GeneratorResult instead of throwing on write errors.
 */
export function write(filePath: string, content: string): GeneratorResult {
  try {
    writeFileSync(filePath, content, "utf-8");
    globalCache.mark(filePath);
    return { file: filePath, success: true };
  } catch (e) {
    return { file: filePath, success: false, error: String(e) };
  }
}

/**
 * Returns the current time as a compact ISO string: "YYYY-MM-DD HH:MM:SS".
 */
export function timestamp(): string {
  return new Date().toISOString().replace("T", " ").substring(0, 19);
}

/**
 * Generates a standard markdown file header used in all generated files.
 */
export function header(title: string, description: string): string {
  return [
    `# ${title}`,
    "",
    `> ${description}`,
    "",
    `_Generated by moodle-mcp on ${timestamp()}_`,
    "",
    "---",
    "",
  ].join("\n");
}

/**
 * Wraps a generator function with an error boundary.
 * Returns a failed GeneratorResult instead of throwing.
 */
export async function safely(
  outputFile: string,
  fn: () => Promise<GeneratorResult>,
): Promise<GeneratorResult> {
  try {
    return await fn();
  } catch (e) {
    return { file: outputFile, success: false, error: String(e) };
  }
}
